footballSquare/frontend

- src/4_Shared/components/Button/index.tsx
- src/4_Shared/components/Button/type.ts
> feat: Button component

- src/0_App/index.tsx
- src/0_App/style/globalStyle.css
- src/0_App/ui/Nav/index.tsx
Nav position을 fixed로 변경하고
body의 padding & height 조정
기존에 body에 padding을 주면 height를 조정하지 않으면 스크롤이 생기는 문제 때문에  sticky로 사용했으나, sticky 사용시, transform등의 속성이 들어가는 태그가 Nav 위로 출력 되는 이슈가 밸생해서 body에 fixed를 주고 height를 추가조정
> chore: Nav postion

- src/0_App/ui/Nav/ui/HomeBtn/index.tsx
- src/2_Widget/MatchModal/ui/StatPanel/ui/PlayerCard/index.tsx
- src/2_Widget/WaitingPlayerList/ui/WaitingPlayerCard/index.tsx
- src/2_Widget/WaitingPlayerList/ui/WaitingPlayerCard/type.ts
> fix: build error

- src/0_App/ui/Nav/index.tsx
nav ui에서 사용하는 navigate url 임시 수정
> chore: nav

- src/1_Page/Login/index.tsx
> feat: temp Login page

- src/1_Page/Community/index.tsx
- src/1_Page/Community/ui/CommunityAdminList/type.d.ts
- src/1_Page/Community/ui/CommunityStaffList/index.tsx
- src/1_Page/Community/ui/CommunityStaffList/type.d.ts
- src/4_Shared/constant/teamRole.ts
- src/4_Shared/util/apiUtil.ts
Admin에서 Staff로 이름 변경, api status 처리 추가
> chore: CommunityStaffList

- src/0_App/ui/Nav/index.tsx
- src/1_Page/Community/index.tsx
- src/1_Page/Community/ui/ChampionShipList/index.tsx
- src/2_Widget/CommunityTeamList/index.tsx
- src/3_Entity/Community/types/request.d.ts
- src/3_Entity/Community/useGetChampionshipList.ts
- src/3_Entity/Community/useGetCommunityInfo.ts
- src/3_Entity/Community/useGetCommunityStaffList.ts
- src/3_Entity/Community/useGetCommunityTeamList.ts
- src/4_Shared/util/apiUtil.ts
> feat: community api 연결

- src/4_Shared/util/apiUtil.ts
> chore: api util

- src/2_Widget/MakeMatchModal/index.tsx
- src/2_Widget/MakeMatchModal/model/type.d.ts
- src/2_Widget/MakeMatchModal/model/usePostMatch.ts
- src/2_Widget/MatchModal/model/useMatchApply.ts
- src/3_Entity/Match/useGetOpenMatchList.ts
- src/4_Shared/zustand/useMakeMatchModalStore.ts
> chore: match make modal

- src/1_Page/FreeMatch/index.tsx
- src/2_Widget/MatchModal/index.tsx
- src/3_Entity/Account/types/request.d.ts
- src/3_Entity/Account/types/response.d.ts
- src/3_Entity/Account/useGetSignIn.ts
- src/3_Entity/Account/useGetUserInfo.ts
- src/3_Entity/Account/usePutProfileImage.ts
- src/3_Entity/Account/usePutUserInfo.ts
> chore: entity

- src/1_Page/Community/index.tsx
- src/1_Page/Community/ui/ChampionShipList/index.tsx
- src/1_Page/Community/ui/CommunityStaffApplicationList/index.tsx
- src/1_Page/Community/ui/CommunityStaffApplicationList/type.d.ts
- src/3_Entity/Community/types/request.d.ts
- src/3_Entity/Community/types/response.d.ts
- src/3_Entity/Community/useDeleteCommunityStaffApplication.ts
- src/3_Entity/Community/useGetCommunityStaffApplicationList.ts
- src/3_Entity/Community/usePostApplyCommunityStaff.ts
- src/3_Entity/Community/usePostApproveCommunityStaffAppication.ts
- src/4_Shared/util/apiUtil.ts
community page에서의 운영진 지원 승인/거절 api 추가
> feat: cummunutiy page api

- package-lock.json
- package.json
- vite.config.ts
@type/node 패키지를 추가하여 개발 환경을 조정하고
vercel 빌드에러를 제거
> chore: dev 환경 설정

- src/0_App/model/useLoadMyInfo.ts
- src/1_Page/FreeMatch/index.tsx
- src/2_Widget/MatchModal/index.tsx
- src/2_Widget/MatchModal/ui/FormationPanel/constant/formation.ts
- src/2_Widget/MatchModal/ui/FormationPanel/index.tsx
- src/3_Entity/Account/usePostSignIn.ts
- src/4_Shared/lib/useMyInfo.ts
> feat: match modal ui

- src/1_Page/Championship/ui/DashBoard/ui/MatchLineupContainer/index.tsx
- src/1_Page/Championship/ui/DashBoard/ui/MatchLineupContainer/ui/EvidenceDetailModal/index.tsx
> fix : 팀기록 null 버그 수정

- src/1_Page/Profile/ui/PlayerDashBoard/index.tsx
- src/1_Page/Profile/ui/PlayerDashBoard/lib/schema.ts
스키마 버그로 인해 
error 메시지 버그 발견 후 수정했습니다
> fix : 스키마 버그 수정

- src/1_Page/Welcome/index.tsx
- src/2_Widget/MatchModal/index.tsx
- src/2_Widget/MatchModal/model/type.d.ts
- src/2_Widget/MatchModal/model/useMatchApprove.ts
- src/3_Entity/Match/types/request.d.ts
- src/3_Entity/Match/usePostMatchApproval.ts
- src/4_Shared/lib/useMyInfo.ts
- src/4_Shared/util/apiUtil.ts
type.d.ts에서의 merge conflict 제거
> fix: merge

- src/1_Page/OAuthHub/index.tsx
- src/1_Page/OAuthHub/model/type.d.ts
- src/1_Page/OAuthHub/model/useDiscord.ts
> fix: oauth login

- src/0_App/ui/Modals/index.tsx
- src/1_Page/Community/index.tsx
- src/1_Page/Community/model/type.d.ts
- src/1_Page/Community/model/useCommunityIdx.ts
- src/1_Page/Community/ui/CommunityBoardList/index.tsx
- src/1_Page/Community/ui/CommunityBoardList/type.d.ts
- src/2_Widget/PostBoardModal/index.tsx
- src/3_Entity/Community/types/request.d.ts
- src/3_Entity/Community/types/response.d.ts
- src/3_Entity/Community/useGetCommunityBoardList.ts
- src/3_Entity/Community/usePostCommunityBoard.ts
- src/4_Shared/hookForm/LoginInput/type.d.ts
- src/4_Shared/hookForm/PostBoardInput/index.tsx
- src/4_Shared/hookForm/PostBoardInput/schema.ts
- src/4_Shared/hookForm/PostBoardInput/type.d.ts
- src/4_Shared/hookForm/SignUpInput/type.d.ts
- src/4_Shared/hookForm/StatInput/type.d.ts
- src/4_Shared/zustand/useCurrentCommunityInfoStore.ts
- src/4_Shared/zustand/usePostBoardModalStore.ts
> feat: community board

- src/1_Page/FreeMatch/index.tsx
make match btn이 로그인 여부에 맞게 출력되도록 수정
> chore: make match btn

- src/3_Entity/Account/useGetDiscordSignIn.ts
- src/3_Entity/Account/usePostCheckAuthSms.ts
> chore: sms api

- src/4_Shared/lib/useMyInfo.ts
팀 탈퇴시 관련 정보 지우는 기능인 함수 
leaveTeam() 구현했습니다 
팀장이 다른사람을 팀장으로 임명하는 경우 teamRoleIdx 0 -> 1  로 변경됩니다 
이에따라 zustand 값도 변동 필요 
setTeamRoleIdx 함수도 추가로 구현했습니다
> feat : useAuthStore leaveTeam , team 관련 정보 지우는 기능 구현

- src/0_App/model/useLoadMyInfo.ts
- src/3_Entity/Account/types/response.d.ts
- src/3_Entity/Account/useGetDiscordSignIn.ts
- src/3_Entity/Account/usePostSignIn.ts
- src/4_Shared/lib/useMyInfo.ts
community_list_idx 로그인시 state로 저장하도록 구현
useAuthStore에 getter 및 setter 함수 업데이트 했습니다.
> feat : useLoadMyInfo - community_list_idx

- src/1_Page/Community/ui/CommunityBoardList/index.tsx
- src/1_Page/Login/index.tsx
- src/1_Page/SignUp/index.tsx
- src/1_Page/SignUp/model/useReceiveAuthSms.ts
- src/3_Entity/Account/usePostCheckAuthSms.ts
- src/3_Entity/Account/usePostReceiveAuthSms.ts
- src/4_Shared/hookForm/SignUpInput/schema.ts
로그인/회원가입 ui 개선을 통해
사용자 편의성을 향상시켰습니다.
> feat: login/signUp UI

- src/2_Widget/PlayerCard/index.tsx
> style :PlayerCard [Widget]

- src/2_Widget/SelectableTeamCard/index.tsx
> style : SelecTableTeamCard

- src/4_Shared/util/apiUtil.ts
> fix: api util

- src/0_App/index.tsx
- src/1_Page/Login/index.tsx
- src/1_Page/Login/model/useFindLoginInfoModal.ts
- src/1_Page/Login/ui/FindLoginInfoModal/index.tsx
- src/1_Page/Login/ui/FindLoginInfoModal/model/useFindLoginInfoTab.ts
- src/1_Page/Login/ui/FindLoginInfoModal/type.d.ts
- src/2_Widget/MakeMatchModal/index.tsx
- src/2_Widget/MatchModal/index.tsx
- src/3_Entity/Account/types/request.d.ts
- src/3_Entity/Account/types/response.d.ts
- src/3_Entity/Account/usePostCheckFindIdSms.ts
- src/3_Entity/Account/usePostCheckFindPwSms.ts
- src/3_Entity/Account/usePostReceiveFindIdSms.ts
- src/3_Entity/Account/usePostReceiveFindPwSms.ts
- src/3_Entity/Account/usePostSignIn.ts
- src/3_Entity/Account/usePutUserPassword.ts
- src/3_Entity/Community/useGetCommunityTeamList.ts
- src/4_Shared/components/ModalLayer/index.tsx
- src/4_Shared/components/ModalLayer/type.d.ts
- src/4_Shared/constant/matchFormation.ts
- src/4_Shared/hookForm/FindIdInput/schema.ts
- src/4_Shared/hookForm/findPwInput/schema.ts
1. id/pw 찾기 기능을 추가했습니다.
2. sms 인증 방식에 대해서, api가 id 찾기 버전과 pw찾기 버전이 명세서상에 나누어져 있었기 때문에 일단 Entity도 분리해두긴 했습니다.
> feat: id/pw 찾기

- src/1_Page/Community/index.tsx
커뮤니티 게시글을 모달에서 작성하지 않고 전용 페이지로 하도록
수정함
> fix: community 게시글 작성 로직 수정

- src/3_Entity/Account/useGetUserInfo.ts
get user info api에서 헤더에 토큰을 같이 넘기도록 수정
> fix: get user info api

- src/1_Page/SignUp/ui/TermOfUseModal/constant/terms.ts
- src/1_Page/SignUp/ui/TermOfUseModal/index.tsx
> chore: 이용 약관

- src/3_Entity/Match/usePostOpenMatch.ts
match 생성시 바로 반영되는 코드가 제거되어서 다시 수정했습니다.
> fix: post match

- src/2_Widget/MakeMatchModal/index.tsx
> fix: match

- src/2_Widget/MakeMatchModal/lib/schema.ts
- src/3_Entity/Match/usePutOpenMatchJoin.ts
match 참여시 응답 alert가 여러번 반복되던 문제 수정
> fix: match apply

- package-lock.json
- package.json
- src/1_Page/ChatTesting/index.tsx
- src/1_Page/Community/model/useCommunityStaffInfo.ts
- src/1_Page/index.tsx
> feat: chat testing page

- src/1_Page/ChatTesting/index.tsx
> chore: socket path

- src/3_Entity/Account/usePostCheckAuthSms.ts
sign up에서 핸드폰번호 인증을 통한 최종 회원가입 과정에
토큰이 임시토큰으로 들어가야하는데 똑바로되어있지 않아
회원가입이 되지 않던 문제 수정
> fix: sign up

- src/1_Page/TeamList/index.tsx
- src/1_Page/TeamList/model/type.d.ts
- src/1_Page/TeamList/model/useTab.ts
- src/1_Page/TeamList/ui/TeamCreatePanel/index.tsx
> style : TeamListPage

- src/1_Page/Boards/index.tsx
페이지 네이션 버튼에서 이전 페이지로 이동되는 버튼이
작동되지 않던 문제 수정
> fix: paging button
